name: cloud native test
on: push
jobs:
    test_job:
        runs-on: ubuntu-latest
        steps:
         - name: checkout
           uses: actions/checkout@v4
         
         - name: List and read the contents
           run: | 
            echo "welcome to cloud native test"
            ls -lrta
            tac README.md

         - name: Generate ASCII art
           run: cosway -f tiger "Beware !, Who is coming ! " >> tiger.txt
           
         #- name: list the content
         #  run: ls
           
         #- name: read the file
         #  run: cat README.md 
        